[package]
name = "serde-rmpv"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rmpv = {version ="1.3.0"}
serde = "1.0.203"
thiserror = "2.0.7"

[dev-dependencies]
serde_derive = "1.0.203"
serde_with = "3.8.1"
