[package]
name = "serde-rmpv"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rmpv = {version ="1.3.0", features = ["with-serde"]}
serde = "1.0.203"
thiserror = "1.0.61"

[dev-dependencies]
serde_derive = "1.0.203"

