#!/bin/sh

set -e 

PROMPT="
Update docs.rs. Make sure ALL functions are documented. 

- Please include all paragraphs of documentation, but omit parameter docs. 
- Format docs to be appropriate for a Rust doc comment text (without the leading ///).
- Use only ASCII. 
- Never include double quotes. 
- Change only what's needed in-place with <replace>.
- In the vim documentation links are written as |link|, please remove the pipes
and enclose the word in bacticks like this: \`word\`.
- Work in batches. I will ask you to continue after reviewing your changes.
"

tenx new
tenx ctx url "https://raw.githubusercontent.com/neovim/neovim/refs/heads/master/runtime/doc/api.txt"
tenx --model deepseek code --prompt "$PROMPT" crates/protoc/src/docs.rs
